USE master ;
GO
---- Full backup
--BACKUP DATABASE UniHospital
--TO DISK = N'C:\Backups\UniHospital_Full.bak'
--WITH COMPRESSION , CHECKSUM , STATS = 10;
--GO
---- Differential backup (run after making changes )
--BACKUP DATABASE UniHospital
--TO DISK = N'C:\ Backups \ UniHospital_Diff.bak '
--WITH DIFFERENTIAL , COMPRESSION , STATS = 10;
--GO
---- Transaction log backup ( database must be in FULL recovery model )
--ALTER DATABASE UniHospital SET RECOVERY FULL ;
--GO
--BACKUP LOG UniHospital
--TO DISK = N'C:\Backups\UniHospital_Log.bak'
--WITH COMPRESSION , STATS = 10;
--GO
-- TODO : Write a point -in - time restore to 10 minutes ago.
-- Hint : RESTORE DATABASE ... WITH STOPAT
USE MASTER;
GO
--TO POINT-IN-TIME RECOVERY;
GO
--RESTORE FULL 
RESTORE DATABASE UNIHOSPITAL
FROM DISK=N'C:\BACKUPS\UNIHOSPITAL_FULL.bak'
WITH NORECOVERY, REPLACE;
GO
--RESTORE DIFFERENTIAL BACKUP
RESTORE DATABASE UNIHOSPITAL FROM DISK=N'C:\BACKUPS\UNIHOSPITAL_DIFF.bak'
WITH NORECOVERY;
GO
--RESTORE LOGTAIL WITH EXPLICIT STOPT PINPOINT
DECLARE @TARGETTIME DATETIME= DATEADD(MINUTE,-10 , GETDATE());
RESTORE LOG UNIHOSPITAL
FROMDISK=N'C:\BACKUPS\UNIHOSPITAL_LOG.bak'
WITH RECOVERY,STOPAT=@TARGETTIME;
GO
ALTER DATABASE UNIHOSPITAL SET MULTI_USER;
GO

--USE MASTER;
--GO
----TO POINT-IN-TIME RECOVERY;
--GO
----RESTORE FULL 
--RESTORE DATABASE UNIHOSPITAL
--FROM DISK=N'C:\BACKUPS\UNIHOSPITAL_FULL.bak'
--WITH NORECOVERY, REPLACE;
--GO
----RESTORE DIFFERENTIAL BACKUP
--RESTORE DATABASE UNIHOSPITAL FROM DISK=N'C:\BACKUPS\UNIHOSPITAL_DIFF.bak'
--WITH NORECOVERY;
--GO
----RESTORE LOGTAIL WITH EXPLICIT STOPT PINPOINT
--DECLARE @TARGETTIME DATETIME= DATEADD(MINUTE,-10 , GETDATE());
--RESTORE LOG UNIHOSPITAL
--FROMDISK=N'C:\BACKUPS\UNIHOSPITAL_LOG.bak'
--WITH RECOVERY,STOPAT=@TARGETTIME;
--GO
--ALTER DATABASE UNIHOSPITAL SET MULTI_USER;
--GO
--USE UniHospital;
--GO

---- Creating Application Roles
--IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'db_clinician' AND type = 'R')
--    CREATE ROLE db_clinician;

--IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'db_billing' AND type = 'R')
--    CREATE ROLE db_billing;

--IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'db_readonly' AND type = 'R')
--    CREATE ROLE db_readonly;
--GO

----Granting permissions
--GRANT SELECT, INSERT, UPDATE ON Appointment TO db_clinician;
--GRANT SELECT, INSERT, UPDATE ON Prescription TO db_clinician;
--GRANT SELECT, INSERT, UPDATE ON Bill TO db_billing;
--GRANT SELECT ON SCHEMA :: dbo TO db_readonly;
--GO

---- 3. Create Server Login First, Then Database User
--IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'CLINICALLOGIN')
--BEGIN
--    -- Server level
--    CREATE LOGIN CLINICALLOGIN WITH PASSWORD = 'Strong_Password_123!'; 
--END
--GO

--IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'CLINICALUSER')
--BEGIN
--    -- Maps the database user
--    CREATE USER CLINICALUSER FOR LOGIN CLINICALLOGIN;
--END
--GO

--ALTER ROLE db_clinician ADD MEMBER CLINICALUSER;
--GO

--DENY SELECT, INSERT, UPDATE, DELETE ON Bill TO db_clinician;
--GO

--IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SECURITY')
--BEGIN
--    EXEC('CREATE SCHEMA SECURITY;');
--END
--GO

---- Step A: Drop the dependent policy first if it exists so we can modify the function
--IF EXISTS (SELECT * FROM sys.security_policies WHERE name = 'SECURITYAPPOINTMENTFILTERPOLICY')
--BEGIN
--    DROP SECURITY POLICY SECURITYAPPOINTMENTFILTERPOLICY;
--END
--GO

--CREATE OR ALTER FUNCTION SECURITY.FN_SECURITYPREDICATEAPPOINTMENTS(@DOCTORID INT)
--RETURNS TABLE
--WITH SCHEMABINDING
--AS
--RETURN 
--    SELECT 1 AS FRI_SECURITY_PREDICATE_RESULT
--    WHERE CAST(SESSION_CONTEXT(N'DOCTORID') AS INT) = @DOCTORID
--       OR IS_MEMBER('db_owner') = 1;
--GO

--CREATE SECURITY POLICY SECURITYAPPOINTMENTFILTERPOLICY
--ADD FILTER PREDICATE SECURITY.FN_SECURITYPREDICATEAPPOINTMENTS(DoctorID) ON dbo.Appointment
--WITH (STATE = ON);
--GO

-- Index fragmentation report
SELECT
OBJECT_NAME (ips . object_id ) AS TableName ,
i. name AS IndexName ,
ips . index_type_desc ,
ROUND (ips . avg_fragmentation_in_percent , 2) AS FragPct ,
ips . page_count
FROM sys . dm_db_index_physical_stats (
DB_ID ('UniHospital'), NULL , NULL , NULL , 'SAMPLED') ips
JOIN sys . indexes i
ON ips . object_id = i. object_id
AND ips . index_id = i. index_id
WHERE ips . page_count > 100
ORDER BY ips . avg_fragmentation_in_percent DESC ;
GO
--IF OBJECT_ID('DBO.MAINTENANCELOG;U') IS NULL
--BEGIN
--CREATE TABLE DBO.MAINTENANCELOG(
--LOGID INT IDENTITY(1,1) PRIMARY KEY,
--EXECUTIONTIME DATE DEFAULT GETDATE(),
-- ACTIONTAKEN NVARCHAR(MAX)
--);
--END
--GO

--CREATE OR ALTER PROCEDURE USP_RUNINDEXMAINTENANCE
--AS
--BEGIN
--SET NOCOUNT ON;
--DECLARE @SQL NVARCHAR(MAX)='';
--DECLARE @LOGSUMMARY NVARCHAR(MAX)='MAINTENANCE SUMMARY:';

----CURSOR PROCESSING LOOP 
--DECLARE INDEXCURSOR CURSOR FOR
--SELECT
--OBJECT_NAME('IPS.OBJECT_ID')AS TABLENAME,
--I.NAME AS INDEXNAME,
--IPS.AVG_FRAGMENTATION_IN_PERCENT AS FRAGPCT
--FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID('UNIHOSPITAL'), NULL, NULL, NULL ,'SAMPLED') IPS
--JOIN SYS.INDEXES I ON IPS.OBJECT_ID=I.OBJECT_ID AND IPS.INDEX_ID=I.INDEX_ID
--WHERE IPS.PAGE_COUNT>100 AND I.NAME IS NOT NULL;

--OPEN INDEXCURSOR;
--DECLARE @TAB NVARCHAR(128), @IDX NVARCHAR(128), @FRAG FLOAT
--FETCH NEXT FROM INDEXCURSOR INTO @TAB,@IDX,@FRAG;
--WHILE @@FETCH_STATUS=0
--BEGIN
----REORGANISE 
--IF @FRAG>=10.0 AND @FRAG<=30.0
--BEGIN
--SET @SQL=CONCAT('ALTER INDEX',QUOTENAME(@IDX),'ON',
--QUOTENAME(@TAB),'REORGANIZE;');
--EXEC SP_EXECUTESQL @SQL;
-- SET @LogSummary = CONCAT(@LogSummary, '[Reorganized', @Idx,'on', @Tab,']');
--END
--ELSE IF @Frag > 30.0
--        BEGIN
--            SET @SQL = CONCAT('ALTER INDEX ', QUOTENAME(@Idx), ' ON ', QUOTENAME(@Tab), ' REBUILD WITH (ONLINE = ON);');
--            -- Fallback syntax verification handler checks if enterprise features missing
--            BEGIN TRY EXEC sp_executesql @SQL; END TRY
--            BEGIN CATCH 
--                SET @SQL = CONCAT('ALTER INDEX ', QUOTENAME(@Idx), ' ON ', QUOTENAME(@Tab), ' REBUILD;');
--                EXEC sp_executesql @SQL;
--            END CATCH
--            SET @LogSummary = CONCAT(@LogSummary, '[Rebuilt ', @Idx, ' on ', @Tab, '] ');
--        END

--        FETCH NEXT FROM IndexCursor INTO @Tab, @Idx, @Frag;
--    END

--CLOSE INDEXCURSOR;
--DEALLOCATE INEXCURSOR;

----(C)UPDATE STATISTICS
--EXEC SP_UPDATESTATS;
--SET @LOGSUMMARY=CONCAT(@LOGSUMMARY,'COMPLETED.');
----D INSERTING 
--INSERT INTO DBO.MAINTENANCELOG(ACTIONTAKEN) VALUES(@LOGSUMMARY);
--END;
--GO

--USE UNIHOSPITAL;
--GO
--THE MAINTENANCELOG 
--IF OBJECT_ID('DBO MAINTENANCELOG,U') IS NULL
--BEGIN
--CREATE TABLE DBO.MAINTENANCELOG (LOGID INT IDENTITY(1,1)PRIMARY KEY,
--EXECUTIONTIME DATETIME DEFAULT GETDATE(),
--ACTIONTAKEN NVARCHAR(MAX));
--END
--GO

----MAINTENANCE SCRIPT ENGINES
--SET NOCOUNT ON;
----DYNAMIC VARIABLES TO HOLD SYSTEM STATES
--DECLARE @TABLENAME NVARCHAR(256);
--DECLARE @INDEXNAME NVARCHAR(256);
--DECLARE @FRAGMENTATION FLOAT;
--DECLARE @DYNAMICSQL NVARCHAR(MAX);
--DECLARE @LOGGEDACTIONS NVARCHAR(MAX)='MAINTENANCE LOG DETAILS:';

----CURSOR LOOP
--DECLARE INDEX_MAINTENANCE_CURSOR CURSOR FOR
--SELECT 
--OBJECT_NAME(IPS.OBJECT_ID) AS TABLENAME,
--I.NAME AS INDEXNAME,
--IPS.AVG_FRAGMENTATION_IN_PERCENT AS FRAGPCT
--FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID('UNIHOSPITAL'),NULL,NULL,NULL,'SAMPLED')IPS
--JOIN sys.indexes i ON ips.object_id = i.object_id AND ips.index_id = i.index_id
--WHERE ips.page_count > 10 AND i.name IS NOT NULL;

--OPEN INDEX_MAINTENANCE_CURSOR;
--FETCH NEXT FROM INDEX_MAINTENANCE_CURSOR INTO @TABLENAME, @INDEXNAME, @FRAGMENTATION;

--WHILE @@FETCH_STATUS=0
--BEGIN
----REORGANISE INDEXES WITH 10 – 30% FRAGMENTATION
--IF @Fragmentation >= 10.0 AND @Fragmentation <= 30.0
--    BEGIN
--        SET @DynamicSQL = N'ALTER INDEX ' + QUOTENAME(@IndexName) + N' ON ' + QUOTENAME(@TableName) + N' REORGANIZE;';
--        EXEC sp_executesql @DynamicSQL;
--          SET @LoggedActions = @LoggedActions + N'[REORGANIZED: ' + @IndexName + N' ON ' + @TableName + N' (Frag: ' + CAST(ROUND(@Fragmentation, 2) AS NVARCHAR(10)) + N'%)];';
--    END
--	IF @Fragmentation >= 10.0 AND @Fragmentation <= 30.0
--    BEGIN
--        SET @DynamicSQL = N'ALTER INDEX ' + QUOTENAME(@IndexName) + N' ON ' + QUOTENAME(@TableName) + N' REORGANIZE;';
--        EXEC sp_executesql @DynamicSQL;
--          SET @LoggedActions = @LoggedActions + N'[REORGANIZED: ' + @IndexName + N' ON ' + @TableName + N' (Frag: ' + CAST(ROUND(@Fragmentation, 2) AS NVARCHAR(10)) + N'%)];';
--    END


--ELSE IF @Fragmentation > 30.0
--    BEGIN
--        -- Tries an ONLINE rebuild first (best practice), falls back to normal rebuild if using standard edition
--        BEGIN TRY
--            SET @DynamicSQL = N'ALTER INDEX ' + QUOTENAME(@IndexName) + N' ON ' + QUOTENAME(@TableName) + N' REBUILD WITH (ONLINE = ON);';
--            EXEC sp_executesql @DynamicSQL;
--        END TRY
--        BEGIN CATCH
--            SET @DynamicSQL = N'ALTER INDEX ' + QUOTENAME(@IndexName) + N' ON ' + QUOTENAME(@TableName) + N' REBUILD;';
--            EXEC sp_executesql @DynamicSQL;
--        END CATCH;

--SET @LOGGEDACTIONS=@LOGGEDACTIONS+N'(STATISTICS:'+@INDEXNAME+N'ON'+@TABLENAME+N'(FRAG:'+CAST(ROUND(@FRAGMENTATION,2)AS NVARCHAR(10))+N'%)];';
--END
--FETCH NEXT FROM INDEX_MAINTENANCE_CURSOR INTO @TABLENAME,@INDEXNAME,@FRAGMENTATION;
--END;

--CLOSE INDEX_MAINTENANCE_CURSOR;
--DEALLOCATE INDEX_MAINTENANCE_CURSOR;

--EXEC SP_UPDATESTATS;
--SET @LOGGEDACTIONS=@LOGGEDACTIONS+'-(STATISTICS SUCCESSFULLY UPDATED ON ALL TABLES)';
--INSERT INTO DBO.MAINTENANCELOG(ACTIONTAKEN)
--VALUES (@LOGGEDACTIONS);
--SELECT * FROM DBO.MAINTENANELOG ORDER BY EXECUTIONTIME DESC;
--GO

